CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Donors" (
    "Id" uuid NOT NULL,
    "FullName" character varying(200) NOT NULL,
    "WeightKg" double precision NOT NULL,
    "BloodGroup" character varying(10),
    "Relation" character varying(100),
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Donors" PRIMARY KEY ("Id")
);

CREATE TABLE "OperationClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    "Name" text NOT NULL,
    CONSTRAINT "PK_OperationClaims" PRIMARY KEY ("Id")
);

CREATE TABLE "Tanks" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Tanks" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    "Email" text NOT NULL,
    "PasswordSalt" bytea NOT NULL,
    "PasswordHash" bytea NOT NULL,
    "AuthenticatorType" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Patients" (
    "Id" uuid NOT NULL,
    "FullName" character varying(200) NOT NULL,
    "WeightKg" double precision NOT NULL,
    "BloodGroup" character varying(10),
    "TransplantType" character varying(20) NOT NULL,
    "Diagnosis" character varying(500),
    "ProtocolNo" character varying(100),
    "BirthDate" timestamp with time zone,
    "DonorId" uuid,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Patients" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Patients_Donors_DonorId" FOREIGN KEY ("DonorId") REFERENCES "Donors" ("Id") ON DELETE SET NULL
);

CREATE TABLE "Racks" (
    "Id" uuid NOT NULL,
    "TankId" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Racks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Racks_Tanks_TankId" FOREIGN KEY ("TankId") REFERENCES "Tanks" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EmailAuthenticators" (
    "Id" uuid NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    "UserId" uuid NOT NULL,
    "ActivationKey" text,
    "IsVerified" boolean NOT NULL,
    CONSTRAINT "PK_EmailAuthenticators" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmailAuthenticators_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "OtpAuthenticators" (
    "Id" uuid NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    "UserId" uuid NOT NULL,
    "SecretKey" bytea NOT NULL,
    "IsVerified" boolean NOT NULL,
    CONSTRAINT "PK_OtpAuthenticators" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OtpAuthenticators_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RefreshTokens" (
    "Id" uuid NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    "UserId" uuid NOT NULL,
    "Token" text NOT NULL,
    "ExpiresDate" timestamp with time zone NOT NULL,
    "CreatedByIp" text NOT NULL,
    "RevokedDate" timestamp with time zone,
    "RevokedByIp" text,
    "ReplacedByToken" text,
    "ReasonRevoked" text,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserOperationClaims" (
    "Id" uuid NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    "UserId" uuid NOT NULL,
    "OperationClaimId" integer NOT NULL,
    CONSTRAINT "PK_UserOperationClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserOperationClaims_OperationClaims_OperationClaimId" FOREIGN KEY ("OperationClaimId") REFERENCES "OperationClaims" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserOperationClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CollectionSessions" (
    "Id" uuid NOT NULL,
    "PatientId" uuid NOT NULL,
    "Day" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "WbcPre" double precision,
    "Hgb" double precision,
    "Hct" double precision,
    "Plt" double precision,
    "VolumeMl" double precision NOT NULL,
    "WBC" double precision NOT NULL,
    "Cd34Percent" double precision NOT NULL,
    "Cd45Percent" double precision NOT NULL,
    "Cd3Percent" double precision NOT NULL,
    "LymphocytePercent" double precision,
    "Mhs" double precision,
    "Cd34PerKg" double precision NOT NULL,
    "Cd3PerKg" double precision NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_CollectionSessions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CollectionSessions_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE
);

CREATE TABLE "DliProducts" (
    "Id" uuid NOT NULL,
    "PatientId" uuid NOT NULL,
    "Cd3PerKg" double precision NOT NULL,
    "VolumeMl" double precision NOT NULL,
    "Notes" character varying(1000),
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_DliProducts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DliProducts_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Boxes" (
    "Id" uuid NOT NULL,
    "RackId" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Boxes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Boxes_Racks_RackId" FOREIGN KEY ("RackId") REFERENCES "Racks" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Products" (
    "Id" uuid NOT NULL,
    "SessionId" uuid NOT NULL,
    "TotalVolume" double precision NOT NULL,
    "TotalWbc" double precision NOT NULL,
    "Cd34Percent" double precision NOT NULL,
    "Cd45Percent" double precision NOT NULL,
    "Cd3Percent" double precision NOT NULL,
    "TotalCd34PerKg" double precision NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Products_CollectionSessions_SessionId" FOREIGN KEY ("SessionId") REFERENCES "CollectionSessions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Slots" (
    "Id" uuid NOT NULL,
    "BoxId" uuid NOT NULL,
    "Position" character varying(20) NOT NULL,
    "IsOccupied" boolean NOT NULL,
    "Version" integer NOT NULL DEFAULT 0,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Slots" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Slots_Boxes_BoxId" FOREIGN KEY ("BoxId") REFERENCES "Boxes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Bags" (
    "Id" uuid NOT NULL,
    "SessionId" uuid NOT NULL,
    "BagNumber" integer NOT NULL,
    "VolumeMl" double precision NOT NULL,
    "SourceVolumeMl" double precision NOT NULL,
    "Cd34PerKg" double precision NOT NULL,
    "Cd3PerKg" double precision NOT NULL,
    "Status" character varying(20) NOT NULL,
    "SlotId" uuid,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Bags" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Bags_CollectionSessions_SessionId" FOREIGN KEY ("SessionId") REFERENCES "CollectionSessions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Bags_Slots_SlotId" FOREIGN KEY ("SlotId") REFERENCES "Slots" ("Id") ON DELETE SET NULL
);

CREATE TABLE "BagMovements" (
    "Id" uuid NOT NULL,
    "BagId" uuid NOT NULL,
    "FromSlotId" uuid,
    "ToSlotId" uuid,
    "Action" character varying(50) NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_BagMovements" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BagMovements_Bags_BagId" FOREIGN KEY ("BagId") REFERENCES "Bags" ("Id") ON DELETE CASCADE
);

INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (1, TIMESTAMPTZ '-infinity', NULL, 'Admin', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (2, TIMESTAMPTZ '-infinity', NULL, 'Auth.Admin', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (3, TIMESTAMPTZ '-infinity', NULL, 'Auth.Read', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (4, TIMESTAMPTZ '-infinity', NULL, 'Auth.Write', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (5, TIMESTAMPTZ '-infinity', NULL, 'Auth.RevokeToken', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (6, TIMESTAMPTZ '-infinity', NULL, 'OperationClaims.Admin', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (7, TIMESTAMPTZ '-infinity', NULL, 'OperationClaims.Read', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (8, TIMESTAMPTZ '-infinity', NULL, 'OperationClaims.Write', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (9, TIMESTAMPTZ '-infinity', NULL, 'OperationClaims.Create', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (10, TIMESTAMPTZ '-infinity', NULL, 'OperationClaims.Update', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (11, TIMESTAMPTZ '-infinity', NULL, 'OperationClaims.Delete', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (12, TIMESTAMPTZ '-infinity', NULL, 'UserOperationClaims.Admin', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (13, TIMESTAMPTZ '-infinity', NULL, 'UserOperationClaims.Read', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (14, TIMESTAMPTZ '-infinity', NULL, 'UserOperationClaims.Write', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (15, TIMESTAMPTZ '-infinity', NULL, 'UserOperationClaims.Create', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (16, TIMESTAMPTZ '-infinity', NULL, 'UserOperationClaims.Update', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (17, TIMESTAMPTZ '-infinity', NULL, 'UserOperationClaims.Delete', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (18, TIMESTAMPTZ '-infinity', NULL, 'Users.Admin', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (19, TIMESTAMPTZ '-infinity', NULL, 'Users.Read', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (20, TIMESTAMPTZ '-infinity', NULL, 'Users.Write', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (21, TIMESTAMPTZ '-infinity', NULL, 'Users.Create', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (22, TIMESTAMPTZ '-infinity', NULL, 'Users.Update', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (23, TIMESTAMPTZ '-infinity', NULL, 'Users.Delete', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (24, TIMESTAMPTZ '-infinity', NULL, 'EmailAuthenticators.Admin', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (25, TIMESTAMPTZ '-infinity', NULL, 'EmailAuthenticators.Read', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (26, TIMESTAMPTZ '-infinity', NULL, 'EmailAuthenticators.Write', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (27, TIMESTAMPTZ '-infinity', NULL, 'EmailAuthenticators.Create', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (28, TIMESTAMPTZ '-infinity', NULL, 'EmailAuthenticators.Update', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (29, TIMESTAMPTZ '-infinity', NULL, 'EmailAuthenticators.Delete', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (30, TIMESTAMPTZ '-infinity', NULL, 'OtpAuthenticators.Admin', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (31, TIMESTAMPTZ '-infinity', NULL, 'OtpAuthenticators.Read', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (32, TIMESTAMPTZ '-infinity', NULL, 'OtpAuthenticators.Write', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (33, TIMESTAMPTZ '-infinity', NULL, 'OtpAuthenticators.Create', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (34, TIMESTAMPTZ '-infinity', NULL, 'OtpAuthenticators.Update', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (35, TIMESTAMPTZ '-infinity', NULL, 'OtpAuthenticators.Delete', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (36, TIMESTAMPTZ '-infinity', NULL, 'RefreshTokens.Admin', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (37, TIMESTAMPTZ '-infinity', NULL, 'RefreshTokens.Read', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (38, TIMESTAMPTZ '-infinity', NULL, 'RefreshTokens.Write', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (39, TIMESTAMPTZ '-infinity', NULL, 'RefreshTokens.Create', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (40, TIMESTAMPTZ '-infinity', NULL, 'RefreshTokens.Update', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (41, TIMESTAMPTZ '-infinity', NULL, 'RefreshTokens.Delete', NULL);

INSERT INTO "Users" ("Id", "AuthenticatorType", "CreatedDate", "DeletedDate", "Email", "PasswordHash", "PasswordSalt", "UpdatedDate")
VALUES ('4767bb64-ab49-42e6-99dc-f9f3d7d1715f', 0, TIMESTAMPTZ '-infinity', NULL, 'narch@kodlama.io', BYTEA E'\\xF718D36B3962AEA0363BA6F10610359F83FC185095F05BF1B21DF0AACF78492AF2D516580B6873C9B91702FD10B525DE9ADAA9BB8FEA348F269C3EE2551B613B', BYTEA E'\\x6EE8E78B8CC4E4A29BFB2B95C6ACE902EE294E47E93C4AA46A88F890EF9FB328D0DE66C3E9C204D23CE6770E695741C3AFFE20F66C7FCFCA73B7BCA8BC86556DF92E6D2AF631D30B03DD569518F93ED882A4A359063BE1DB504CC53714A2F1B2D1B8D821509688948D873D584D7AE0C4A0176EBDD30165388EA046E913DD7C15', NULL);

INSERT INTO "UserOperationClaims" ("Id", "CreatedDate", "DeletedDate", "OperationClaimId", "UpdatedDate", "UserId")
VALUES ('2caa40aa-3f5b-4046-a22f-2f796fd857f0', TIMESTAMPTZ '-infinity', NULL, 1, NULL, '4767bb64-ab49-42e6-99dc-f9f3d7d1715f');

CREATE INDEX "IX_BagMovements_BagId" ON "BagMovements" ("BagId");

CREATE INDEX "IX_Bags_SessionId" ON "Bags" ("SessionId");

CREATE UNIQUE INDEX "IX_Bags_SlotId" ON "Bags" ("SlotId") WHERE "SlotId" IS NOT NULL;

CREATE UNIQUE INDEX "IX_Boxes_RackId_Name" ON "Boxes" ("RackId", "Name");

CREATE INDEX "IX_CollectionSessions_PatientId" ON "CollectionSessions" ("PatientId");

CREATE INDEX "IX_DliProducts_PatientId" ON "DliProducts" ("PatientId");

CREATE INDEX "IX_EmailAuthenticators_UserId" ON "EmailAuthenticators" ("UserId");

CREATE INDEX "IX_OtpAuthenticators_UserId" ON "OtpAuthenticators" ("UserId");

CREATE INDEX "IX_Patients_DonorId" ON "Patients" ("DonorId");

CREATE UNIQUE INDEX "IX_Products_SessionId" ON "Products" ("SessionId");

CREATE UNIQUE INDEX "IX_Racks_TankId_Name" ON "Racks" ("TankId", "Name");

CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");

CREATE UNIQUE INDEX "IX_Slots_BoxId_Position" ON "Slots" ("BoxId", "Position");

CREATE UNIQUE INDEX "IX_Tanks_Name" ON "Tanks" ("Name");

CREATE INDEX "IX_UserOperationClaims_OperationClaimId" ON "UserOperationClaims" ("OperationClaimId");

CREATE INDEX "IX_UserOperationClaims_UserId" ON "UserOperationClaims" ("UserId");

SELECT setval(
    pg_get_serial_sequence('"OperationClaims"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "OperationClaims") + 1,
        nextval(pg_get_serial_sequence('"OperationClaims"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260420133905_InitialCreate', '8.0.8');

COMMIT;

START TRANSACTION;

DELETE FROM "UserOperationClaims"
WHERE "Id" = '2caa40aa-3f5b-4046-a22f-2f796fd857f0';

DELETE FROM "Users"
WHERE "Id" = '4767bb64-ab49-42e6-99dc-f9f3d7d1715f';

ALTER TABLE "Bags" ADD "Purpose" character varying(20) NOT NULL DEFAULT '';

ALTER TABLE "Bags" ADD "SplitBatchId" uuid;

INSERT INTO "Users" ("Id", "AuthenticatorType", "CreatedDate", "DeletedDate", "Email", "PasswordHash", "PasswordSalt", "UpdatedDate")
VALUES ('bb29564d-751e-4159-99f2-205c172b1c01', 0, TIMESTAMPTZ '-infinity', NULL, 'narch@kodlama.io', BYTEA E'\\xC0BFEAB67232EF8A71ECD680E8C0E032B4FEC5A30E4C067785C865A77E100874655048AFB3DE4FFD4E723451B945D5596406F1FBAAB3D35142C839FDC96337D6', BYTEA E'\\x13E9326281A3FB1D6D3085AD87FB83DB103407F01AFDF502441360C99BC8119301DA3958D92B183234288A9FC5AC919C1CC5EC477506C17A70372FDE6BA58DCAB2606678D06AFA1D1CA6F767E38B64DECFAF8475A821752EAB2A050504A35F8932D776F86615CE7B7F3F16359C7C60ECBF66D1DA11F92CB41A04D8DCF7393D09', NULL);

INSERT INTO "UserOperationClaims" ("Id", "CreatedDate", "DeletedDate", "OperationClaimId", "UpdatedDate", "UserId")
VALUES ('86828272-3b4e-47cc-bad0-8360f7e5972a', TIMESTAMPTZ '-infinity', NULL, 1, NULL, 'bb29564d-751e-4159-99f2-205c172b1c01');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260420135528_AddBagPurposeAndSplitBatch', '8.0.8');

COMMIT;

START TRANSACTION;

DELETE FROM "UserOperationClaims"
WHERE "Id" = '86828272-3b4e-47cc-bad0-8360f7e5972a';

DELETE FROM "Users"
WHERE "Id" = 'bb29564d-751e-4159-99f2-205c172b1c01';

INSERT INTO "Users" ("Id", "AuthenticatorType", "CreatedDate", "DeletedDate", "Email", "PasswordHash", "PasswordSalt", "UpdatedDate")
VALUES ('def5d923-1b48-462f-9d6d-82636d27a211', 0, TIMESTAMPTZ '-infinity', NULL, 'narch@kodlama.io', BYTEA E'\\x618F26E6961FAB3201B0D930CEC7D0DB07179813D8F78EB1F60431ADC28AC85B16291B9CE26CC4C6C8FF2599C012A56E461CDC50AE423382219769BBF04B9B52', BYTEA E'\\xFA72A99EF59D8972DC32793B7E081FA70F03BE9CB729670AD6517A74F88A8DE3EFA3803006E4EDAF564E0B54CFF63534C7E155D227EEEB5F2BB876ED7D5ED4F1B0068CDD943387D895AED169A093296F529335563B93C49DDC4871E44D33EB23C87208C24EFF9DD998683B013201C020C82DA27F21C6632122F6222E792899C8', NULL);

INSERT INTO "UserOperationClaims" ("Id", "CreatedDate", "DeletedDate", "OperationClaimId", "UpdatedDate", "UserId")
VALUES ('947e94a0-cc2d-4f94-8b4e-1578e269e710', TIMESTAMPTZ '-infinity', NULL, 1, NULL, 'def5d923-1b48-462f-9d6d-82636d27a211');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260420140934_init', '8.0.8');

COMMIT;

START TRANSACTION;

DELETE FROM "UserOperationClaims"
WHERE "Id" = '947e94a0-cc2d-4f94-8b4e-1578e269e710';

DELETE FROM "Users"
WHERE "Id" = 'def5d923-1b48-462f-9d6d-82636d27a211';

INSERT INTO "Users" ("Id", "AuthenticatorType", "CreatedDate", "DeletedDate", "Email", "PasswordHash", "PasswordSalt", "UpdatedDate")
VALUES ('29efa6f9-9bda-4830-a9a7-17372ad77c9d', 0, TIMESTAMPTZ '-infinity', NULL, 'narch@kodlama.io', BYTEA E'\\xF9F41D3BA97D005BF117BC674D77100DD2823B720F04FAF780A0E1C05601F1A7783EB950CFBA97FCF2D70553BC0C5A94124602719263EF8D8FF81A29F855E4BD', BYTEA E'\\xA7FCBCCAE839A73B40EDEF2FE4895DF5668C69049C7490D63FE395D4F8EC5031DA886BE4E5D6CE62B0641E2A8364745F7314E6D4BFE7FF6D3A55E7DC4847340DCBF84E335200BA725B6981716F076D3A5F165EA042E2E951EB7DAFE279E9C8084BC7B97BA19059494D9D8ADAD05595D0A328C3B321B5D8558BA35C5B94577F56', NULL);

INSERT INTO "UserOperationClaims" ("Id", "CreatedDate", "DeletedDate", "OperationClaimId", "UpdatedDate", "UserId")
VALUES ('a12be4f7-593d-4c8b-9497-898b798fccf7', TIMESTAMPTZ '-infinity', NULL, 1, NULL, '29efa6f9-9bda-4830-a9a7-17372ad77c9d');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260420144045_seedim', '8.0.8');

COMMIT;

START TRANSACTION;

DELETE FROM "UserOperationClaims"
WHERE "Id" = 'a12be4f7-593d-4c8b-9497-898b798fccf7';

DELETE FROM "Users"
WHERE "Id" = '29efa6f9-9bda-4830-a9a7-17372ad77c9d';

ALTER TABLE "Donors" ADD "BirthDate" timestamp with time zone;

ALTER TABLE "Donors" ADD "DonorType" character varying(20) NOT NULL DEFAULT 'Related';

ALTER TABLE "DliProducts" ADD "Cd3Percent" double precision;

ALTER TABLE "DliProducts" ADD "Date" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "DliProducts" ADD "DonorId" uuid;

ALTER TABLE "DliProducts" ADD "LymphocytePercent" double precision;

ALTER TABLE "DliProducts" ADD "SessionId" uuid;

ALTER TABLE "DliProducts" ADD "TotalCd3" double precision NOT NULL DEFAULT 0.0;

ALTER TABLE "DliProducts" ADD "Wbc" double precision;

ALTER TABLE "CollectionSessions" ADD "HctPost" double precision;

ALTER TABLE "CollectionSessions" ADD "HgbPost" double precision;

ALTER TABLE "CollectionSessions" ADD "PltPost" double precision;

ALTER TABLE "CollectionSessions" ADD "PreCd34Percent" double precision;

ALTER TABLE "CollectionSessions" ADD "PreCd45Percent" double precision;

ALTER TABLE "CollectionSessions" ADD "PreMhs" double precision;

ALTER TABLE "CollectionSessions" ADD "WbcPost" double precision;

ALTER TABLE "Bags" ADD "Cd34Percent" double precision;

ALTER TABLE "Bags" ADD "Cd3Percent" double precision;

ALTER TABLE "Bags" ADD "Cd45Percent" double precision;

ALTER TABLE "Bags" ADD "CompositionNote" character varying(120);

ALTER TABLE "Bags" ADD "Wbc" double precision;

INSERT INTO "Users" ("Id", "AuthenticatorType", "CreatedDate", "DeletedDate", "Email", "PasswordHash", "PasswordSalt", "UpdatedDate")
VALUES ('08fcbbaa-6256-4645-9872-63687afac7e7', 0, TIMESTAMPTZ '-infinity', NULL, 'narch@kodlama.io', BYTEA E'\\x00AEF1AB54385D7D9605CD4CC5E13754F6A5541808C2661BC13BDB82C25FE7CFC5AD820A1210AD083D831A085407FAD3E7FF344FA659BDF0293DED77D251AD6B', BYTEA E'\\xE9F02FEF0DD6E035E77ED7905C614C502EE52126BC0D26A9D7701FCFDD0FB0CBA6BAA5E375334CFB7D7EEEC9CA0280984EFC5C45A69F01E679E31AEDC1F96FD7F2E543F45ED5C7F5E9C68AB21B82B427FA9D4A83379474D5E135D3E07F57DC86862E0FB73E214EED9E602654DB6D25E5701FF94B6097C2EBB85D42B35EFCCDD5', NULL);

INSERT INTO "UserOperationClaims" ("Id", "CreatedDate", "DeletedDate", "OperationClaimId", "UpdatedDate", "UserId")
VALUES ('9cd5d801-8800-45d9-bddf-7873b23693ad', TIMESTAMPTZ '-infinity', NULL, 1, NULL, '08fcbbaa-6256-4645-9872-63687afac7e7');

CREATE INDEX "IX_DliProducts_DonorId" ON "DliProducts" ("DonorId");

CREATE INDEX "IX_DliProducts_SessionId" ON "DliProducts" ("SessionId");

ALTER TABLE "DliProducts" ADD CONSTRAINT "FK_DliProducts_CollectionSessions_SessionId" FOREIGN KEY ("SessionId") REFERENCES "CollectionSessions" ("Id") ON DELETE SET NULL;

ALTER TABLE "DliProducts" ADD CONSTRAINT "FK_DliProducts_Donors_DonorId" FOREIGN KEY ("DonorId") REFERENCES "Donors" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260420164749_AddSessionPreFlowAndBagWbcAndDliDetails', '8.0.8');

COMMIT;

START TRANSACTION;

DELETE FROM "UserOperationClaims"
WHERE "Id" = '9cd5d801-8800-45d9-bddf-7873b23693ad';

DELETE FROM "Users"
WHERE "Id" = '08fcbbaa-6256-4645-9872-63687afac7e7';

INSERT INTO "Users" ("Id", "AuthenticatorType", "CreatedDate", "DeletedDate", "Email", "PasswordHash", "PasswordSalt", "UpdatedDate")
VALUES ('baefffe2-6b04-415f-a333-93cfd03021f2', 0, TIMESTAMPTZ '-infinity', NULL, 'narch@kodlama.io', BYTEA E'\\xF4A1D2344F32F63D8319A19B4BCABF771B4C0861B9E6F85EC02173205B9B594CD0EBB10E0121A30A447A5BCA1DE972FE0666998834C6B7B37692F59E8A0F4E61', BYTEA E'\\x2D3FB5FE9892CF0798F7578D7F7C9B3B90CC78D358FD22237A09CA121CC4EF7D9A29AFCE77B0BCD7547D028D4DD2ABC2E96154D501949304FDE7095CBCC1D5B38FA1D34358919D9844F7C0A7C93EAA486F2F0452FBA149D45B96453C24A6C56396A26070463709DA29A8FD8D111BE023506097B7BB071357E761BA449403688A', NULL);

INSERT INTO "UserOperationClaims" ("Id", "CreatedDate", "DeletedDate", "OperationClaimId", "UpdatedDate", "UserId")
VALUES ('1e8c0269-1aee-4041-be81-c6d28d3b2eb2', TIMESTAMPTZ '-infinity', NULL, 1, NULL, 'baefffe2-6b04-415f-a333-93cfd03021f2');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260420183927_AddPlcIndustrialMonitoring', '8.0.8');

COMMIT;

START TRANSACTION;

DELETE FROM "UserOperationClaims"
WHERE "Id" = '1e8c0269-1aee-4041-be81-c6d28d3b2eb2';

DELETE FROM "Users"
WHERE "Id" = 'baefffe2-6b04-415f-a333-93cfd03021f2';

CREATE TABLE "PlcAlarmContacts" (
    "Id" uuid NOT NULL,
    "DevicePrefix" character varying(32),
    "DisplayName" character varying(200) NOT NULL,
    "Phone" character varying(32) NOT NULL,
    "Email" character varying(256),
    "SmsEnabled" boolean NOT NULL,
    "EmailEnabled" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_PlcAlarmContacts" PRIMARY KEY ("Id")
);

CREATE TABLE "PlcSensorPoints" (
    "Id" uuid NOT NULL,
    "SensorCode" character varying(64) NOT NULL,
    "DeviceName" character varying(200) NOT NULL,
    "DevicePrefix" character varying(32) NOT NULL,
    "DataLabel" character varying(64) NOT NULL,
    "ModbusHost" character varying(128) NOT NULL,
    "ModbusPort" integer NOT NULL,
    "SlaveId" integer NOT NULL,
    "RegisterAddress" integer NOT NULL,
    "RegisterLength" integer NOT NULL,
    "ScaleDivisor" double precision NOT NULL,
    "PollIntervalSeconds" integer NOT NULL,
    "AlarmLow" double precision,
    "AlarmHigh" double precision,
    "AlarmActive" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_PlcSensorPoints" PRIMARY KEY ("Id")
);

CREATE TABLE "PlcTelemetryReadings" (
    "Id" uuid NOT NULL,
    "SensorPointId" uuid NOT NULL,
    "Value" double precision NOT NULL,
    "ReadAtUtc" timestamp with time zone NOT NULL,
    "RawRegisterValue" integer,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_PlcTelemetryReadings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PlcTelemetryReadings_PlcSensorPoints_SensorPointId" FOREIGN KEY ("SensorPointId") REFERENCES "PlcSensorPoints" ("Id") ON DELETE CASCADE
);

INSERT INTO "Users" ("Id", "AuthenticatorType", "CreatedDate", "DeletedDate", "Email", "PasswordHash", "PasswordSalt", "UpdatedDate")
VALUES ('b8e3fbb5-e99c-4d74-8d82-447d0e8734c3', 0, TIMESTAMPTZ '-infinity', NULL, 'narch@kodlama.io', BYTEA E'\\xEAC247483B341F292A97890441873C02E05937F67C44487DB326DD9212DB818B024F2E048234D4F94C16D24731718963023D4AB6CB5EFC36FB2574D280C58520', BYTEA E'\\xEEB9E36AD7C0990728FCE1603A244032863127C769F2932B5ABA16B64CFAC688A3EAACD484A8C73A261416C4ECAB1DE6A7B3FD7B2FEBFD469A73BE0E29249A4BD99863733B2F60ACC79C21F4183425458A6DC23B9BC4B0617E0DEFE5DA005B03146D310C7C0637E92347A5592BD5FE164B69BCD35CD10578B89EF4AF2D15A7B6', NULL);

INSERT INTO "UserOperationClaims" ("Id", "CreatedDate", "DeletedDate", "OperationClaimId", "UpdatedDate", "UserId")
VALUES ('12688ce4-9bd8-4d7c-84ff-150d953a4760', TIMESTAMPTZ '-infinity', NULL, 1, NULL, 'b8e3fbb5-e99c-4d74-8d82-447d0e8734c3');

CREATE UNIQUE INDEX "IX_PlcSensorPoints_SensorCode" ON "PlcSensorPoints" ("SensorCode");

CREATE INDEX "IX_PlcTelemetryReadings_SensorPointId_ReadAtUtc" ON "PlcTelemetryReadings" ("SensorPointId", "ReadAtUtc");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260420184028_AddPlcIndustrialEntities', '8.0.8');

COMMIT;

START TRANSACTION;

CREATE TABLE "ClinicalSettings" (
    "Id" uuid NOT NULL,
    "SessionCd34Cd3Divisor" double precision NOT NULL,
    "DliCd3CalculationDivisor" double precision NOT NULL,
    "TargetCd34AutologousPerKg" double precision NOT NULL,
    "TargetCd34AllogeneicPerKg" double precision NOT NULL,
    "IdealCd34AutologousPerKg" double precision NOT NULL,
    "IdealCd34AllogeneicPerKg" double precision NOT NULL,
    "MaxApheresisDaysAutologous" integer NOT NULL,
    "MaxApheresisDaysAllogeneic" integer NOT NULL,
    "DliHighDoseCd3PerKgThreshold" double precision NOT NULL,
    "ProductMinimumCd34PerKg" double precision NOT NULL,
    "DashboardCd34LowThreshold" double precision NOT NULL,
    "DashboardCd34ElevatedFloor" double precision NOT NULL,
    "DashboardCd3HighRiskThreshold" double precision NOT NULL,
    "DashboardCd3LowImmuneThreshold" double precision NOT NULL,
    "DashboardCd3OptimalMin" double precision NOT NULL,
    "DashboardCd3OptimalMax" double precision NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_ClinicalSettings" PRIMARY KEY ("Id")
);

INSERT INTO "ClinicalSettings" ("Id", "SessionCd34Cd3Divisor", "DliCd3CalculationDivisor", "TargetCd34AutologousPerKg", "TargetCd34AllogeneicPerKg", "IdealCd34AutologousPerKg", "IdealCd34AllogeneicPerKg", "MaxApheresisDaysAutologous", "MaxApheresisDaysAllogeneic", "DliHighDoseCd3PerKgThreshold", "ProductMinimumCd34PerKg", "DashboardCd34LowThreshold", "DashboardCd34ElevatedFloor", "DashboardCd3HighRiskThreshold", "DashboardCd3LowImmuneThreshold", "DashboardCd3OptimalMin", "DashboardCd3OptimalMax", "CreatedDate", "UpdatedDate", "DeletedDate")
VALUES ('11111111-1111-1111-1111-111111111111', 10000.0, 10000.0, 2.0, 4.0, 4.0, 5.0, 4, 2, 10.0, 2.0, 2.0, 4.0, 10.0, 2.0, 3.0, 8.0, TIMESTAMPTZ '2026-04-20T00:00:00Z', NULL, NULL);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260420211401_AddClinicalSettingsTable', '8.0.8');

COMMIT;

START TRANSACTION;

DELETE FROM "UserOperationClaims"
WHERE "Id" = '1526e8bd-347c-4986-b3de-40cc1da33d83';

DELETE FROM "Users"
WHERE "Id" = '8bcfdd9f-640e-45f6-a5a4-c153eadd9718';

ALTER TABLE "Bags" DROP CONSTRAINT "FK_Bags_Slots_SlotId";

ALTER TABLE "Slots" DROP CONSTRAINT "FK_Slots_Boxes_BoxId";

ALTER TABLE "Boxes" DROP CONSTRAINT "FK_Boxes_Racks_RackId";

DROP INDEX "IX_Bags_SlotId";

ALTER TABLE "Slots" RENAME TO "BagCells";

DO $ef$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint c
    JOIN pg_class t ON c.conrelid = t.oid
    JOIN pg_namespace n ON t.relnamespace = n.oid
    WHERE n.nspname = 'public' AND t.relname = 'BagCells' AND c.conname = 'PK_Slots' AND c.contype = 'p'
  ) THEN
    ALTER TABLE "BagCells" RENAME CONSTRAINT "PK_Slots" TO "PK_BagCells";
  ELSIF NOT EXISTS (
    SELECT 1 FROM pg_constraint c
    JOIN pg_class t ON c.conrelid = t.oid
    JOIN pg_namespace n ON t.relnamespace = n.oid
    WHERE n.nspname = 'public' AND t.relname = 'BagCells' AND c.contype = 'p'
  ) THEN
    ALTER TABLE "BagCells" ADD CONSTRAINT "PK_BagCells" PRIMARY KEY ("Id");
  END IF;
END $ef$;

DO $ef$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_class i
    JOIN pg_namespace n ON i.relnamespace = n.oid
    WHERE n.nspname = 'public' AND i.relkind = 'i' AND i.relname = 'IX_Slots_BoxId_Position'
  ) THEN
    ALTER INDEX "IX_Slots_BoxId_Position" RENAME TO "IX_BagCells_BoxId_Position";
  ELSIF NOT EXISTS (
    SELECT 1 FROM pg_class i
    JOIN pg_namespace n ON i.relnamespace = n.oid
    WHERE n.nspname = 'public' AND i.relkind = 'i' AND i.relname = 'IX_BagCells_BoxId_Position'
  ) THEN
    CREATE UNIQUE INDEX "IX_BagCells_BoxId_Position" ON "BagCells" ("BoxId", "Position");
  END IF;
END $ef$;

CREATE TABLE "RackSlots" (
    "Id" uuid NOT NULL,
    "RackId" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_RackSlots" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RackSlots_Racks_RackId" FOREIGN KEY ("RackId") REFERENCES "Racks" ("Id") ON DELETE CASCADE
);

ALTER TABLE "Boxes" ADD "SlotId" uuid;

INSERT INTO "RackSlots" ("Id", "RackId", "Name", "CreatedDate", "UpdatedDate", "DeletedDate")
SELECT gen_random_uuid(), b."RackId", '__b' || replace(b."Id"::text, '-', ''), b."CreatedDate", b."UpdatedDate", b."DeletedDate"
FROM "Boxes" b;

UPDATE "Boxes" b
SET "SlotId" = rs."Id"
FROM "RackSlots" rs
WHERE rs."Name" = '__b' || replace(b."Id"::text, '-', '');

ALTER TABLE "Boxes" ALTER COLUMN "SlotId" SET NOT NULL;

DROP INDEX "IX_Boxes_RackId_Name";

ALTER TABLE "Boxes" DROP COLUMN "RackId";

ALTER TABLE "Bags" RENAME COLUMN "SlotId" TO "BagCellId";

ALTER TABLE "BagMovements" RENAME COLUMN "ToSlotId" TO "ToBagCellId";

ALTER TABLE "BagMovements" RENAME COLUMN "FromSlotId" TO "FromBagCellId";

CREATE UNIQUE INDEX "IX_Bags_BagCellId" ON "Bags" ("BagCellId") WHERE "BagCellId" IS NOT NULL;

CREATE UNIQUE INDEX "IX_Boxes_SlotId_Name" ON "Boxes" ("SlotId", "Name");

CREATE UNIQUE INDEX "IX_RackSlots_RackId_Name" ON "RackSlots" ("RackId", "Name");

ALTER TABLE "Bags" ADD CONSTRAINT "FK_Bags_BagCells_BagCellId" FOREIGN KEY ("BagCellId") REFERENCES "BagCells" ("Id") ON DELETE SET NULL;

ALTER TABLE "Boxes" ADD CONSTRAINT "FK_Boxes_RackSlots_SlotId" FOREIGN KEY ("SlotId") REFERENCES "RackSlots" ("Id") ON DELETE CASCADE;

ALTER TABLE "BagCells" ADD CONSTRAINT "FK_BagCells_Boxes_BoxId" FOREIGN KEY ("BoxId") REFERENCES "Boxes" ("Id") ON DELETE CASCADE;

INSERT INTO "Users" ("Id", "AuthenticatorType", "CreatedDate", "DeletedDate", "Email", "PasswordHash", "PasswordSalt", "UpdatedDate")
VALUES ('eb180b88-f92d-4bc1-a351-59778f738a03', 0, TIMESTAMPTZ '-infinity', NULL, 'narch@kodlama.io', BYTEA E'\\xECC2F38A0D3E3BB55306D5DE41FA70A5865B5E7EA09F912ACB90FB49A6C8CE6102AFE9C5ED075C6A9A86A1CDA801F61C0D04BC22CCAC5DED42DBEDC8CCA369B4', BYTEA E'\\xF563DA5D001BF07C28DEC351158AFDFE46634D3CE22E580488CA052E0EC5C16A9105517467E40A52D963E74F3998CD12ADA1ADDF13B62015EC99E82891B6C5953E4B7337A1D490C9EEDA2F24EC3D10D76715B5AB39BDEE7A002076A284810BAE9ABCB81D85DA4A07350178F7DF116EFB504B631F90018A88ED5F7FC8431CAA5D', NULL);

INSERT INTO "UserOperationClaims" ("Id", "CreatedDate", "DeletedDate", "OperationClaimId", "UpdatedDate", "UserId")
VALUES ('b48afbfc-1fe8-4a62-b24a-a66ab29b9cde', TIMESTAMPTZ '-infinity', NULL, 1, NULL, 'eb180b88-f92d-4bc1-a351-59778f738a03');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260424092530_CryoRackSlotBagCellHierarchy', '8.0.8');

COMMIT;

START TRANSACTION;

DELETE FROM "UserOperationClaims"
WHERE "Id" = 'b48afbfc-1fe8-4a62-b24a-a66ab29b9cde';

DELETE FROM "Users"
WHERE "Id" = 'eb180b88-f92d-4bc1-a351-59778f738a03';

ALTER TABLE "Patients" ADD "IdentityNumber" character varying(20);

ALTER TABLE "Donors" ADD "IdentityNumber" character varying(20);

INSERT INTO "Users" ("Id", "AuthenticatorType", "CreatedDate", "DeletedDate", "Email", "PasswordHash", "PasswordSalt", "UpdatedDate")
VALUES ('58fdc981-eef5-4045-be96-7d21c04caf12', 0, TIMESTAMPTZ '-infinity', NULL, 'narch@kodlama.io', BYTEA E'\\xD041672262EA0E7E9C94861FD55BBD148D59D5A26E4056EAF4743DE3B2621A7FB2895F2C6E296C301AFA6093347B0F424BDABE8D362848FB58E714FBBC62D6B8', BYTEA E'\\x70668ECC0353EFE2D4F06CD5E188D241CEC781469D17A697AC143B8DFAD95BA97147E9FF6860B9BC20B7460DCBA6BCDC1C20034F9A0CF1153867CE8F97284770B36AD672A011498780A4B19897A8139ABEEC2FBAB6D1682AC1020BF15A48FEF6B50E601875A15F02EC16EDD25933FF723697DF6C95C417ECEC7C49056C85D653', NULL);

INSERT INTO "UserOperationClaims" ("Id", "CreatedDate", "DeletedDate", "OperationClaimId", "UpdatedDate", "UserId")
VALUES ('6a0693c8-ed3e-49f8-a993-1c027cc530ae', TIMESTAMPTZ '-infinity', NULL, 1, NULL, '58fdc981-eef5-4045-be96-7d21c04caf12');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260505211038_AddPatientDonorIdentityNumber', '8.0.8');

COMMIT;

START TRANSACTION;

DELETE FROM "UserOperationClaims"
WHERE "Id" = '6a0693c8-ed3e-49f8-a993-1c027cc530ae';

DELETE FROM "Users"
WHERE "Id" = '58fdc981-eef5-4045-be96-7d21c04caf12';

INSERT INTO "Users" ("Id", "AuthenticatorType", "CreatedDate", "DeletedDate", "Email", "PasswordHash", "PasswordSalt", "UpdatedDate")
VALUES ('1d883cf3-8187-47b3-8e8e-e3eb68daf4fe', 0, TIMESTAMPTZ '-infinity', NULL, 'narch@kodlama.io', BYTEA E'\\x999F3D046852F85297877C5618F9CE0FDC5D1ACB257BDECBFC3FEE7814AB6018E03EDE718D6D244DA7AD0E70E3AA3D918A19996373B1A17CE2C91314D16E84EF', BYTEA E'\\x31E018E22A474E7F43DABB009F545B8CEB6A11873784241A3B76AD35717FF1A6B74040A423DE5170CD76CAE69A0E5CED7414F5AFDEBBFF843AA25D1EAC846A93915A9B55D6A4A86714894A06BF4398AAC5B7686584964002D11576BE1D8F2C98B31B4215048752471B1656212052A3F9FD8868A5EEAAA2DEDAAC05279A341065', NULL);

INSERT INTO "UserOperationClaims" ("Id", "CreatedDate", "DeletedDate", "OperationClaimId", "UpdatedDate", "UserId")
VALUES ('11971417-bbba-4e30-b97b-f7262a3fd4c5', TIMESTAMPTZ '-infinity', NULL, 1, NULL, '1d883cf3-8187-47b3-8e8e-e3eb68daf4fe');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260505232520_AddClinicalSettingsOperationClaims', '8.0.8');

COMMIT;

START TRANSACTION;


                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (42, '0001-01-01 00:00:00', 'Bags.Admin', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (43, '0001-01-01 00:00:00', 'Bags.Read', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (44, '0001-01-01 00:00:00', 'Bags.Write', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (45, '0001-01-01 00:00:00', 'Bags.Create', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (46, '0001-01-01 00:00:00', 'Bags.Update', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (47, '0001-01-01 00:00:00', 'Bags.Delete', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (48, '0001-01-01 00:00:00', 'Bags.CreateRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (49, '0001-01-01 00:00:00', 'Bags.UpdateRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (50, '0001-01-01 00:00:00', 'Bags.DeleteRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (51, '0001-01-01 00:00:00', 'BagMovements.Admin', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (52, '0001-01-01 00:00:00', 'BagMovements.Read', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (53, '0001-01-01 00:00:00', 'BagMovements.Write', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (54, '0001-01-01 00:00:00', 'BagMovements.Create', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (55, '0001-01-01 00:00:00', 'BagMovements.Update', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (56, '0001-01-01 00:00:00', 'BagMovements.Delete', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (57, '0001-01-01 00:00:00', 'BagMovements.CreateRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (58, '0001-01-01 00:00:00', 'BagMovements.UpdateRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (59, '0001-01-01 00:00:00', 'BagMovements.DeleteRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (60, '0001-01-01 00:00:00', 'Boxes.Admin', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (61, '0001-01-01 00:00:00', 'Boxes.Read', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (62, '0001-01-01 00:00:00', 'Boxes.Write', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (63, '0001-01-01 00:00:00', 'Boxes.Create', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (64, '0001-01-01 00:00:00', 'Boxes.Update', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (65, '0001-01-01 00:00:00', 'Boxes.Delete', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (66, '0001-01-01 00:00:00', 'Boxes.CreateRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (67, '0001-01-01 00:00:00', 'Boxes.UpdateRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (68, '0001-01-01 00:00:00', 'Boxes.DeleteRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (69, '0001-01-01 00:00:00', 'CollectionSessions.Admin', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (70, '0001-01-01 00:00:00', 'CollectionSessions.Read', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (71, '0001-01-01 00:00:00', 'CollectionSessions.Write', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (72, '0001-01-01 00:00:00', 'CollectionSessions.Create', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (73, '0001-01-01 00:00:00', 'CollectionSessions.Update', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (74, '0001-01-01 00:00:00', 'CollectionSessions.Delete', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (75, '0001-01-01 00:00:00', 'CollectionSessions.CreateRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (76, '0001-01-01 00:00:00', 'CollectionSessions.UpdateRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (77, '0001-01-01 00:00:00', 'CollectionSessions.DeleteRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (78, '0001-01-01 00:00:00', 'DliProducts.Admin', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (79, '0001-01-01 00:00:00', 'DliProducts.Read', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (80, '0001-01-01 00:00:00', 'DliProducts.Write', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (81, '0001-01-01 00:00:00', 'DliProducts.Create', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (82, '0001-01-01 00:00:00', 'DliProducts.Update', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (83, '0001-01-01 00:00:00', 'DliProducts.Delete', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (84, '0001-01-01 00:00:00', 'DliProducts.CreateRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (85, '0001-01-01 00:00:00', 'DliProducts.UpdateRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (86, '0001-01-01 00:00:00', 'DliProducts.DeleteRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (87, '0001-01-01 00:00:00', 'Donors.Admin', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (88, '0001-01-01 00:00:00', 'Donors.Read', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (89, '0001-01-01 00:00:00', 'Donors.Write', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (90, '0001-01-01 00:00:00', 'Donors.Create', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (91, '0001-01-01 00:00:00', 'Donors.Update', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (92, '0001-01-01 00:00:00', 'Donors.Delete', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (93, '0001-01-01 00:00:00', 'Donors.CreateRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (94, '0001-01-01 00:00:00', 'Donors.UpdateRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (95, '0001-01-01 00:00:00', 'Donors.DeleteRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (96, '0001-01-01 00:00:00', 'Patients.Admin', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (97, '0001-01-01 00:00:00', 'Patients.Read', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (98, '0001-01-01 00:00:00', 'Patients.Write', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (99, '0001-01-01 00:00:00', 'Patients.Create', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (100, '0001-01-01 00:00:00', 'Patients.Update', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (101, '0001-01-01 00:00:00', 'Patients.Delete', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (102, '0001-01-01 00:00:00', 'Patients.CreateRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (103, '0001-01-01 00:00:00', 'Patients.UpdateRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (104, '0001-01-01 00:00:00', 'Patients.DeleteRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (105, '0001-01-01 00:00:00', 'Products.Admin', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (106, '0001-01-01 00:00:00', 'Products.Read', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (107, '0001-01-01 00:00:00', 'Products.Write', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (108, '0001-01-01 00:00:00', 'Products.Create', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (109, '0001-01-01 00:00:00', 'Products.Update', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (110, '0001-01-01 00:00:00', 'Products.Delete', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (111, '0001-01-01 00:00:00', 'Products.CreateRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (112, '0001-01-01 00:00:00', 'Products.UpdateRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (113, '0001-01-01 00:00:00', 'Products.DeleteRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (114, '0001-01-01 00:00:00', 'Racks.Admin', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (115, '0001-01-01 00:00:00', 'Racks.Read', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (116, '0001-01-01 00:00:00', 'Racks.Write', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (117, '0001-01-01 00:00:00', 'Racks.Create', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (118, '0001-01-01 00:00:00', 'Racks.Update', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (119, '0001-01-01 00:00:00', 'Racks.Delete', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (120, '0001-01-01 00:00:00', 'Racks.CreateRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (121, '0001-01-01 00:00:00', 'Racks.UpdateRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (122, '0001-01-01 00:00:00', 'Racks.DeleteRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (123, '0001-01-01 00:00:00', 'Slots.Admin', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (124, '0001-01-01 00:00:00', 'Slots.Read', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (125, '0001-01-01 00:00:00', 'Slots.Write', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (126, '0001-01-01 00:00:00', 'Slots.Create', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (127, '0001-01-01 00:00:00', 'Slots.Update', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (128, '0001-01-01 00:00:00', 'Slots.Delete', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (129, '0001-01-01 00:00:00', 'Slots.CreateRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (130, '0001-01-01 00:00:00', 'Slots.UpdateRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (131, '0001-01-01 00:00:00', 'Slots.DeleteRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (132, '0001-01-01 00:00:00', 'Tanks.Admin', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (133, '0001-01-01 00:00:00', 'Tanks.Read', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (134, '0001-01-01 00:00:00', 'Tanks.Write', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (135, '0001-01-01 00:00:00', 'Tanks.Create', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (136, '0001-01-01 00:00:00', 'Tanks.Update', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (137, '0001-01-01 00:00:00', 'Tanks.Delete', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (138, '0001-01-01 00:00:00', 'Tanks.CreateRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (139, '0001-01-01 00:00:00', 'Tanks.UpdateRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (140, '0001-01-01 00:00:00', 'Tanks.DeleteRange', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (141, '0001-01-01 00:00:00', 'ClinicalSettings.Admin', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (142, '0001-01-01 00:00:00', 'ClinicalSettings.Read', NULL, NULL);
                INSERT INTO "OperationClaims" ("Id", "CreatedDate", "Name", "UpdatedDate", "DeletedDate") VALUES (143, '0001-01-01 00:00:00', 'ClinicalSettings.Write', NULL, NULL);
            

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260506000001_AddAllMissingOperationClaims', '8.0.8');

COMMIT;

START TRANSACTION;


                UPDATE "OperationClaims"
                SET "UpdatedDate" = NULL
                WHERE "UpdatedDate" = '-infinity'::timestamp with time zone;

                UPDATE "OperationClaims"
                SET "DeletedDate" = NULL
                WHERE "DeletedDate" = '-infinity'::timestamp with time zone;

                UPDATE "OperationClaims"
                SET "CreatedDate" = '0001-01-01 00:00:00+00'::timestamp with time zone
                WHERE "CreatedDate" = '-infinity'::timestamp with time zone;
            

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260506000002_FixOperationClaimInfinityDates', '8.0.8');

COMMIT;

START TRANSACTION;


                UPDATE "OperationClaims"
                SET "CreatedDate" = '0001-01-01 00:00:00+00'::timestamp with time zone
                WHERE NOT isfinite("CreatedDate");

                UPDATE "OperationClaims"
                SET "UpdatedDate" = NULL
                WHERE "UpdatedDate" IS NOT NULL AND NOT isfinite("UpdatedDate");

                UPDATE "OperationClaims"
                SET "DeletedDate" = NULL
                WHERE "DeletedDate" IS NOT NULL AND NOT isfinite("DeletedDate");
            

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260506000003_NormalizeOperationClaimTimestamps', '8.0.8');

COMMIT;

START TRANSACTION;


                UPDATE "OperationClaims"
                SET "CreatedDate" = '2000-01-01 00:00:00+00'::timestamptz
                WHERE "CreatedDate" < '0001-01-01 00:00:00+00'::timestamptz;
            

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260506000004_FixOperationClaimLowerBoundCreatedDate', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE "Bags" ADD "UseReason" character varying(20);

ALTER TABLE "Bags" ADD "UseNote" character varying(500);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260507000001_AddBagUseReasonAndNote', '8.0.8');

COMMIT;

START TRANSACTION;

DELETE FROM "UserOperationClaims"
WHERE "Id" = '11971417-bbba-4e30-b97b-f7262a3fd4c5';

DELETE FROM "Users"
WHERE "Id" = '1d883cf3-8187-47b3-8e8e-e3eb68daf4fe';

ALTER TABLE "BagMovements" ADD "UsedAt" timestamp with time zone;

INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (42, TIMESTAMPTZ '-infinity', NULL, 'Bags.Admin', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (43, TIMESTAMPTZ '-infinity', NULL, 'Bags.Read', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (44, TIMESTAMPTZ '-infinity', NULL, 'Bags.Write', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (45, TIMESTAMPTZ '-infinity', NULL, 'Bags.Create', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (46, TIMESTAMPTZ '-infinity', NULL, 'Bags.Update', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (47, TIMESTAMPTZ '-infinity', NULL, 'Bags.Delete', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (48, TIMESTAMPTZ '-infinity', NULL, 'Bags.CreateRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (49, TIMESTAMPTZ '-infinity', NULL, 'Bags.UpdateRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (50, TIMESTAMPTZ '-infinity', NULL, 'Bags.DeleteRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (51, TIMESTAMPTZ '-infinity', NULL, 'BagMovements.Admin', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (52, TIMESTAMPTZ '-infinity', NULL, 'BagMovements.Read', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (53, TIMESTAMPTZ '-infinity', NULL, 'BagMovements.Write', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (54, TIMESTAMPTZ '-infinity', NULL, 'BagMovements.Create', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (55, TIMESTAMPTZ '-infinity', NULL, 'BagMovements.Update', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (56, TIMESTAMPTZ '-infinity', NULL, 'BagMovements.Delete', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (57, TIMESTAMPTZ '-infinity', NULL, 'BagMovements.CreateRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (58, TIMESTAMPTZ '-infinity', NULL, 'BagMovements.UpdateRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (59, TIMESTAMPTZ '-infinity', NULL, 'BagMovements.DeleteRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (60, TIMESTAMPTZ '-infinity', NULL, 'Boxes.Admin', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (61, TIMESTAMPTZ '-infinity', NULL, 'Boxes.Read', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (62, TIMESTAMPTZ '-infinity', NULL, 'Boxes.Write', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (63, TIMESTAMPTZ '-infinity', NULL, 'Boxes.Create', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (64, TIMESTAMPTZ '-infinity', NULL, 'Boxes.Update', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (65, TIMESTAMPTZ '-infinity', NULL, 'Boxes.Delete', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (66, TIMESTAMPTZ '-infinity', NULL, 'Boxes.CreateRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (67, TIMESTAMPTZ '-infinity', NULL, 'Boxes.UpdateRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (68, TIMESTAMPTZ '-infinity', NULL, 'Boxes.DeleteRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (69, TIMESTAMPTZ '-infinity', NULL, 'CollectionSessions.Admin', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (70, TIMESTAMPTZ '-infinity', NULL, 'CollectionSessions.Read', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (71, TIMESTAMPTZ '-infinity', NULL, 'CollectionSessions.Write', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (72, TIMESTAMPTZ '-infinity', NULL, 'CollectionSessions.Create', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (73, TIMESTAMPTZ '-infinity', NULL, 'CollectionSessions.Update', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (74, TIMESTAMPTZ '-infinity', NULL, 'CollectionSessions.Delete', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (75, TIMESTAMPTZ '-infinity', NULL, 'CollectionSessions.CreateRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (76, TIMESTAMPTZ '-infinity', NULL, 'CollectionSessions.UpdateRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (77, TIMESTAMPTZ '-infinity', NULL, 'CollectionSessions.DeleteRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (78, TIMESTAMPTZ '-infinity', NULL, 'DliProducts.Admin', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (79, TIMESTAMPTZ '-infinity', NULL, 'DliProducts.Read', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (80, TIMESTAMPTZ '-infinity', NULL, 'DliProducts.Write', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (81, TIMESTAMPTZ '-infinity', NULL, 'DliProducts.Create', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (82, TIMESTAMPTZ '-infinity', NULL, 'DliProducts.Update', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (83, TIMESTAMPTZ '-infinity', NULL, 'DliProducts.Delete', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (84, TIMESTAMPTZ '-infinity', NULL, 'DliProducts.CreateRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (85, TIMESTAMPTZ '-infinity', NULL, 'DliProducts.UpdateRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (86, TIMESTAMPTZ '-infinity', NULL, 'DliProducts.DeleteRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (87, TIMESTAMPTZ '-infinity', NULL, 'Donors.Admin', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (88, TIMESTAMPTZ '-infinity', NULL, 'Donors.Read', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (89, TIMESTAMPTZ '-infinity', NULL, 'Donors.Write', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (90, TIMESTAMPTZ '-infinity', NULL, 'Donors.Create', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (91, TIMESTAMPTZ '-infinity', NULL, 'Donors.Update', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (92, TIMESTAMPTZ '-infinity', NULL, 'Donors.Delete', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (93, TIMESTAMPTZ '-infinity', NULL, 'Donors.CreateRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (94, TIMESTAMPTZ '-infinity', NULL, 'Donors.UpdateRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (95, TIMESTAMPTZ '-infinity', NULL, 'Donors.DeleteRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (96, TIMESTAMPTZ '-infinity', NULL, 'Patients.Admin', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (97, TIMESTAMPTZ '-infinity', NULL, 'Patients.Read', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (98, TIMESTAMPTZ '-infinity', NULL, 'Patients.Write', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (99, TIMESTAMPTZ '-infinity', NULL, 'Patients.Create', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (100, TIMESTAMPTZ '-infinity', NULL, 'Patients.Update', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (101, TIMESTAMPTZ '-infinity', NULL, 'Patients.Delete', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (102, TIMESTAMPTZ '-infinity', NULL, 'Patients.CreateRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (103, TIMESTAMPTZ '-infinity', NULL, 'Patients.UpdateRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (104, TIMESTAMPTZ '-infinity', NULL, 'Patients.DeleteRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (105, TIMESTAMPTZ '-infinity', NULL, 'Products.Admin', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (106, TIMESTAMPTZ '-infinity', NULL, 'Products.Read', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (107, TIMESTAMPTZ '-infinity', NULL, 'Products.Write', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (108, TIMESTAMPTZ '-infinity', NULL, 'Products.Create', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (109, TIMESTAMPTZ '-infinity', NULL, 'Products.Update', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (110, TIMESTAMPTZ '-infinity', NULL, 'Products.Delete', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (111, TIMESTAMPTZ '-infinity', NULL, 'Products.CreateRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (112, TIMESTAMPTZ '-infinity', NULL, 'Products.UpdateRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (113, TIMESTAMPTZ '-infinity', NULL, 'Products.DeleteRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (114, TIMESTAMPTZ '-infinity', NULL, 'Racks.Admin', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (115, TIMESTAMPTZ '-infinity', NULL, 'Racks.Read', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (116, TIMESTAMPTZ '-infinity', NULL, 'Racks.Write', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (117, TIMESTAMPTZ '-infinity', NULL, 'Racks.Create', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (118, TIMESTAMPTZ '-infinity', NULL, 'Racks.Update', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (119, TIMESTAMPTZ '-infinity', NULL, 'Racks.Delete', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (120, TIMESTAMPTZ '-infinity', NULL, 'Racks.CreateRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (121, TIMESTAMPTZ '-infinity', NULL, 'Racks.UpdateRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (122, TIMESTAMPTZ '-infinity', NULL, 'Racks.DeleteRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (123, TIMESTAMPTZ '-infinity', NULL, 'Slots.Admin', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (124, TIMESTAMPTZ '-infinity', NULL, 'Slots.Read', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (125, TIMESTAMPTZ '-infinity', NULL, 'Slots.Write', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (126, TIMESTAMPTZ '-infinity', NULL, 'Slots.Create', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (127, TIMESTAMPTZ '-infinity', NULL, 'Slots.Update', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (128, TIMESTAMPTZ '-infinity', NULL, 'Slots.Delete', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (129, TIMESTAMPTZ '-infinity', NULL, 'Slots.CreateRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (130, TIMESTAMPTZ '-infinity', NULL, 'Slots.UpdateRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (131, TIMESTAMPTZ '-infinity', NULL, 'Slots.DeleteRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (132, TIMESTAMPTZ '-infinity', NULL, 'Tanks.Admin', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (133, TIMESTAMPTZ '-infinity', NULL, 'Tanks.Read', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (134, TIMESTAMPTZ '-infinity', NULL, 'Tanks.Write', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (135, TIMESTAMPTZ '-infinity', NULL, 'Tanks.Create', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (136, TIMESTAMPTZ '-infinity', NULL, 'Tanks.Update', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (137, TIMESTAMPTZ '-infinity', NULL, 'Tanks.Delete', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (138, TIMESTAMPTZ '-infinity', NULL, 'Tanks.CreateRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (139, TIMESTAMPTZ '-infinity', NULL, 'Tanks.UpdateRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (140, TIMESTAMPTZ '-infinity', NULL, 'Tanks.DeleteRange', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (141, TIMESTAMPTZ '-infinity', NULL, 'ClinicalSettings.Admin', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (142, TIMESTAMPTZ '-infinity', NULL, 'ClinicalSettings.Read', NULL);
INSERT INTO "OperationClaims" ("Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate")
VALUES (143, TIMESTAMPTZ '-infinity', NULL, 'ClinicalSettings.Write', NULL);

INSERT INTO "Users" ("Id", "AuthenticatorType", "CreatedDate", "DeletedDate", "Email", "PasswordHash", "PasswordSalt", "UpdatedDate")
VALUES ('5378d2a0-92d2-4ae2-9b88-69f4c0664782', 0, TIMESTAMPTZ '-infinity', NULL, 'narch@kodlama.io', BYTEA E'\\xFDD4D77CB031E3BC19E4780D8A91DCD7156C9ACC8B8998FA8871F5AA0A893F1E1963643320F050D4EE93EE60343A9577E83E9C343DE62DC15EA5BBAEE3ADE91F', BYTEA E'\\xD2882F4CB6D527FA74E8034083847CDA942D7B973CEFF1C265C514D07D8BA0E4046E6DB1A837C82D4B7CFD84F206324FBDD517AF83214F742E10333316451756EFCF03A2B8751A600FD0F62FAEB14BE78940CC823DA86D6C2E0D6CD444ECDDE841C68AE42D9ED61D0A90033AE377D16A89F02AAF6162FA03C49FCF0A35E256A4', NULL);

INSERT INTO "UserOperationClaims" ("Id", "CreatedDate", "DeletedDate", "OperationClaimId", "UpdatedDate", "UserId")
VALUES ('71aecea9-f407-4da1-9912-00f00fd0d879', TIMESTAMPTZ '-infinity', NULL, 1, NULL, '5378d2a0-92d2-4ae2-9b88-69f4c0664782');

SELECT setval(
    pg_get_serial_sequence('"OperationClaims"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "OperationClaims") + 1,
        nextval(pg_get_serial_sequence('"OperationClaims"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260507121325_AddBagMovementUsedAt', '8.0.8');

COMMIT;

